name: Windows_v12

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
      - run: DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V
      - run: Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V
